// infoarena - Plimbare 3
// Lúcio Cardoso

// Solution:

// Suppose 1 is the root of the tree. If we remove the edge (u, v), where u is a child from 1, the answer
// to this edge will be the sum of the diameters of the trees generated by removing this edge + 1.

// Fix the tree arbitrarily (at first, at 1). Let diam[u] be the largest among all diameters in the subtrees of a child of u. Also, let
// d[0][u] and d[1][u] be the greatest and second greatest paths going down from u, where the children that u passes
// through in both paths are distinct. Finally, let maior[u] be the diameter in the subtree of u.

// We can find diam[] and d[][] by using a single DFS. Also, note that maior[u] = max(diam[u], d[0][u]+d[1][u]).

// Finally, we can use the "spin trick" to find the answer for every edge (based on the first fact mentioned above) by trying
// every possible vertex as root of the tree, and updating the respective values diam[], dist[][] and maior[]. For the details,
// check the code below.

#include <bits/stdc++.h>

using namespace std;

typedef pair<int, int> pii;

const int maxn = 2e5+10;

int d[3][maxn], diam[2][maxn], maior[maxn];

int ans[maxn];

vector<pii> grafo[maxn];

void dfs1(int u, int p)
{
	for (auto pp: grafo[u])
	{
		int v = pp.first;
		if (v == p) continue;

		dfs1(v, u);

		if (maior[v] > diam[0][u])
			diam[1][u] = diam[0][u], diam[0][u] = maior[v];
		else if (maior[v] > diam[1][u])
			diam[1][u] = maior[v];

		if (d[0][v]+1 > d[0][u])
			d[2][u] = d[1][u], d[1][u] = d[0][u], d[0][u] = d[0][v]+1;
		else if (d[0][v]+1 > d[1][u])
			d[2][u] = d[1][u], d[1][u] = d[0][v]+1;
		else if (d[0][v]+1 > d[2][u])
			d[2][u] = d[0][v]+1;
	}

	maior[u] = max(diam[0][u], d[0][u]+d[1][u]);
}

void solve(int u, int p)
{
	for (auto pp: grafo[u])
	{
		int v = pp.first, e = pp.second;
		if (v == p) continue;

		int ant[4] = {d[0][u], d[1][u], diam[0][u], maior[u]};

		if (d[0][v]+1 == d[0][u])
		{
			d[0][u] = d[1][u];
			d[1][u] = d[2][u];
		}
		else if (d[0][v]+1 == d[1][u])
		{
			d[1][u] = d[2][u];
		}

		if (diam[0][u] == maior[v])
			diam[0][u] = diam[1][u];

		maior[u] = max(diam[0][u], d[0][u]+d[1][u]);

		ans[e] = maior[v]+maior[u]+1;

		if (maior[u] > diam[0][v])
			diam[1][v] = diam[0][v], diam[0][v] = maior[u];
		else if (maior[u] > diam[1][v])
			diam[1][v] = maior[u];

		if (d[0][u]+1 > d[0][v])
			d[2][v] = d[1][v], d[1][v] = d[0][v], d[0][v] = d[0][u]+1;
		else if (d[0][u]+1 > d[1][v])
			d[2][v] = d[1][v], d[1][v] = d[0][u]+1;
		else if (d[0][u]+1 > d[2][v])
			d[2][v] = d[0][u]+1;

		maior[v] = max(diam[0][v], d[0][v]+d[1][v]);

		solve(v, u);

		d[0][u] = ant[0], d[1][u] = ant[1], diam[0][u] = ant[2], maior[u] = ant[3];
	}
}

int main(void)
{
	freopen("plimbare3.in", "r", stdin);
	freopen("plimbare3.out", "w", stdout);

	int n;
	scanf("%d", &n);

	for (int i = 1; i < n; i++)
	{
		int u, v;
		scanf("%d %d", &u, &v);

		grafo[u].push_back({v, i});
		grafo[v].push_back({u, i});
	}

	dfs1(1, 0);
	solve(1, 0);

	for (int i = 1; i < n; i++)
		printf("%d\n", ans[i]);
}
